version: "3"

services:
  backend:
    network_mode: bridge
    image: stopcovid/stopcovid:lan
    build:
      context: .
      dockerfile: Dockerfile.lan
    links:
      - database
      - redis-server
    labels:
      traefik.enable: "true"
      traefik.backend: "stop-covid-api"
      traefik.ws.port: 80
      traefik.frontend.rule: "Host:api.stop-covid.dev.soyhuce.lan"

  peerjs:
    network_mode: bridge
    image: peerjs/peerjs-server
    ports:
      - "6001:9000"
    labels:
      traefik.enable: "true"
      traefik.backend: "stop-covid-rtc"
      traefik.ws.port: 6001
      traefik.frontend.rule: "Host:peer.stop-covid.dev.soyhuce.lan"

  database:
    network_mode: bridge
    image: harbor.soyhuce.lan/internal/database:latest

  redis-server:
    network_mode: bridge
    image: redis:3.2
