FROM php:7.4-apache
LABEL MAINTAINER="Bastien Philippe <bastien.philippe@soyhuce.fr>"

RUN mkdir -p /usr/share/man/man1 \
    && mkdir -p /usr/share/man/man7

# Install packages for php extensions
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libcurl4-gnutls-dev \
    libxml2-dev\
    libonig-dev \
    zlib1g-dev \
    libzip-dev \
    curl \
    libpng-dev \
    libjpeg62-turbo-dev \
    libgd3 \
    postgresql-client

# Install & configure php extension from sources
RUN docker-php-ext-install -j$(nproc) \
                                  json \
                                  dom \
                                  curl \
                                  bcmath \
                                  mbstring \
                                  pgsql \
                                  pdo_pgsql \
                                  gd \
                                  zip

# Add x-debug
RUN pecl install xdebug-2.9.0 \
    && docker-php-ext-enable xdebug

# Add en_US.UTF-8 locale
RUN apt-get install -y locales && \
  sed -i -e "s/# en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen && \
  echo "LANG=en_US.UTF-8">/etc/default/locale && \
  dpkg-reconfigure --frontend=noninteractive locales

ENV LC_COLLATE en_US.UTF-8

# Customize PHP conf using a custom php.ini
COPY php-app.ini /usr/local/etc/php/conf.d/php-app.ini

# Copy application sources into default apache2 directory
WORKDIR /var/www
COPY . /var/www
